---
abstract: 'PSGI support for EntityModel::Web framework'
author:
  - 'Tom Molesworth <tom@entitymodel.com>'
build_requires:
  EntityModel::Web: 0.003
  PSGI: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: EntityModel-Web-PSGI
version: 0.001
